@host=http://localhost:5261

GET  {{host}}/flags
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MDMwZGI3Mi1kNzQxLTQ4YWMtYTViNi05N2Y4MWQ5MTBmM2EiLCJnaXZlbl9uYW1lIjoiSWx5YSIsImZhbWlseV9uYW1lIjoiVHJ1a2hpbiIsImp0aSI6IjYxNjAxMGNmLWVlY2UtNDU2YS04MDEwLWQ3NDY3YTk0NmVlMiIsImV4cCI6MTcxMTk0MjAwNSwiaXNzIjoiRmxhZ3MiLCJhdWQiOiJGbGFncyJ9.4vxjAkWjSn7srh9hwYQZ_xFB3uz_ZPnt_VJbpXZ72VU