version: '3.9'

networks:
  ishop-network:
    driver: bridge

services:
  backend:
    container_name: ishop
    build:
      context: ./server
      dockerfile: IShop.Api/Dockerfile
    ports:
      - "5000:80"
    networks:
      - ishop-network
    depends_on:
      - postgres_db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DB=Host=postgres_db;Port=5432;Database=ishop;User Id=postgres;Password=Nhe[bY202$3;
  postgres_db:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nhe[bY202$3
      POSTGRES_DB: ishop
    ports:
      - "5432:5432"
    networks:
      - ishop-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
  frontend:
    image: frontend
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - backend
  nginx: 
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - frontend
      - backend
    networks:
      - ishop-network

volumes:
  postgres-data:
   