@host=http://localhost:5261

POST {{host}}/auth/register
Content-Type: application/json

{
	"firstName": "Ilya",
	"lastName":"Trukhin",
	"email": "ilya.trukhin.99@mail.ru",
	"phone": "79146447079",
	"password": "qwer1234"
}